name: 'Pull Request notification for tasks'
description: 'This action is used to send notification to eXo Tasks during the Pull Request workflow (creation, approval, closing, merge).'
inputs:
  SERVER_URL:
    description: Target Server URL
    required: true
  SERVER_DEFAULT_SITENAME:
    description: Target Server Default Sitename
    required: false
    default: "dw"
  SERVER_USERNAME:
    description: Target Server username
    required: true
  SERVER_PASSWORD:
    description: Target Server user password
    required: true
  TASKS_REGEX_FILTER:
    description: Pull request tasks regex filter
    required: false
    default: "(task|maint|exo)((-|_)[0-9]{4,})+"
  GITHUB_TOKEN:
    description: Github token (default repository token)
    required: false
    default: ""
runs:
  using: 'node20'
  main: 'dist/index.js'