name: 'Pull Request notification for tasks'
description: 'This action is used to send notification to eXo Tasks during the Pull Request workflow (creation, approval, closing, merge).'
inputs:
  SERVER_URL:
    description: Target Server URL
    required: true
  SERVER_DEFAULT_SITENAME:
    description: Target Server Default Sitename
    required: false
    default: "dw"
  SERVER_USERNAME:
    description: Target Server username
    required: true
  SERVER_PASSWORD:
    description: Target Server user password
    required: true
  TASKS_REGEX_FILTER:
    description: Pull request tasks regex filter
    required: false
    default: "(task|maint|exo)((-|_)[0-9]{4,})+"
runs:
  using: "composite"
  steps:
    - name: PLF Tasks Webhook
      shell: bash
      run: |
        doGetCurl() {
          curl -A "PR Webhook Tasks/1.0" -s -f -L -u ${SERVER_USERNAME}:${SERVER_PASSWORD} -XGET $*
        }
        if [[ ! ${base_branch_name} =~ ^(master|develop(-exo|-meed)?|feature\/[A-Za-z-]+[0-9]?|stable\/[0-9]+(\.[0-9]+)*\.x)$ ]]; then
          echo "❌ Branch ${base_branch_name} is not supported for Task notification. Abort"
          exit 0
        fi
        if [[ ${creator} =~ ^(dependabot\[bot\]|snyk-bot)$ ]]; then
          echo "❌ PR created with Bot users is not supported for Task notification. Abort"
          exit 0
        fi
        if ! echo ${message:-} | grep -qioP "${TASKS_REGEX_FILTER}"; then
          echo "No tasks found! Abort."
          exit 0
        fi
        TASKS_IDS="$(echo ${message:-} | grep -ioP "${TASKS_REGEX_FILTER}" | grep -oP '[0-9]+' | xargs)"
        echo "OK Task(s) found! Starting notifications..."
        reducedBaseBranchName=$(echo ${base_branch_name} | sed -e 's|feature/||gi' -e 's|stable/||gi')
        link="PR <a href=\"https://github.com/${full_repo_name}/pull/${pull_number}\" title="${full_repo_name}#${pull_number}:${base_branch_name}" target="_blank">${repo_name}#${pull_number}:${reducedBaseBranchName}</a>"
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          if [ "${{ github.event.action }}" = "review_requested" ]; then
              echo "Requested reviewer is: ${requested_reviewer}."
              msg="💭 $link requested a review from <tt>${requested_reviewer}</tt>"
          elif [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            shortCommitId=$(echo ${{ github.event.pull_request.merge_commit_sha }} | cut -c1-7)
            mergeMethod="merged"
            if [ "${{ github.event.pull_request.auto_merge }}" != "null" ] && [ "${{ github.event.pull_request.auto_merge }}" != "" ]; then 
              mergeMethod="auto ${{ github.event.pull_request.auto_merge.merge_method }}-merged"
            fi
            mergedCommitlink="<a href=\"https://github.com/${full_repo_name}/commit/${{ github.event.pull_request.merge_commit_sha }}\" target="_blank">${shortCommitId}</a>"
            base_branch_link="<a href=\"https://github.com/${full_repo_name}/tree/${base_branch_name}\" target="_blank">${base_branch_name}</a>"
            mergerGithubUser="${{ github.event.pull_request.merged_by.login }}"
            msg="🌟 $link has <tt>${mergeMethod}</tt> ${mergedCommitlink} into ${base_branch_link} by <tt>${mergerGithubUser}</tt>."
          elif [ "${{ github.event.action }}" = "closed" ]; then
            msg="🍂 $link has been <tt>${{ github.event.action }}</tt>."
          elif [ "${{ github.event.action }}" = "opened" ]; then
            msg="🌱 $link has been <tt>created</tt>."
          elif [ "${{ github.event.action }}" = "reopened" ]; then
            msg="🍃 $link has been <tt>${{ github.event.action }}</tt>."
          else
            msg="ℹ️ $link has been <tt>${{ github.event.action }}</tt>."
          fi
        elif [ "${{ github.event_name }}" = "pull_request_review" ] && [ "${{ github.event.action }}" = "submitted" ]; then
          reviewerGithubUser="${{ github.event.review.user.login }}"
          reviewEventLink="${{ github.event.review.html_url }}"
          if [ "${{ github.event.review.state }}" = "changes_requested" ]; then
            requestChangesEventLink="<a href=\"$reviewEventLink\">changes</a>"
            msg="🛠️ $link requires ${requestChangesEventLink} from <tt>${reviewerGithubUser}</tt>."
          elif [ "${{ github.event.review.state }}" = "approved" ]; then
            approvedEventLink="<a href=\"$reviewEventLink\">approved</a>"
            msg="✅ $link has been ${approvedEventLink} by <tt>${reviewerGithubUser}</tt>."
          else
            stateEventLink="<a href=\"$reviewEventLink\">${{ github.event.review.state }}</a>"
            msg="ℹ️ $link has been ${stateEventLink}."
          fi
        fi
        echo "*** Message is:"
        echo ${msg}
        echo "***"
        for TASK_ID in ${TASKS_IDS}; do
          echo "Commenting to Task #${TASK_ID}..."
          curl -so /dev/null -w '%{http_code}' --retry 3 --retry-max-time 60 -L -u ${SERVER_USERNAME}:${SERVER_PASSWORD} -XPOST --data-raw "<p>${msg}</p>" "${SERVER_TASK_REST_PREFIXE_URL}/comments/${TASK_ID}"
        done
      env:
        SERVER_URL: ${{ inputs.SERVER_URL }}
        SERVER_USERNAME: ${{ inputs.SERVER_USERNAME }}
        SERVER_PASSWORD: ${{ inputs.SERVER_PASSWORD }}
        SERVER_TASK_REST_PREFIXE_URL: ${{ inputs.SERVER_URL }}/rest/private/tasks
        TASKS_REGEX_FILTER: ${{ inputs.TASKS_REGEX_FILTER }}
        SERVER_DEFAULT_SITENAME: ${{ inputs.SERVER_DEFAULT_SITENAME }}
        message: ${{ github.event.pull_request.title }}
        state: ${{ github.event.pull_request.state }}
        pull_number: ${{ github.event.pull_request.number }}
        requested_reviewer: ${{ github.event.requested_reviewer.login }}
        creator: ${{ github.event.pull_request.user.login }}
        full_repo_name: ${{ github.event.repository.full_name }}
        repo_name: ${{ github.event.repository.name }}
        base_branch_name: ${{ github.event.pull_request.base.ref }}

branding:
  icon: "bell"
  color: "gray-dark"
